export interface Question {
  id: number;
  text: string;
  imageUrl?: string;
  options: string[];
  correct: number;
}

export const questions: Question[] = [
  { id: 1, text: "Toshbaqa 1 minutda 2 metr yo'l bosadi. 150 metrni necha soatda bosib o'tadi.", options: ["1 soat", "1,25 soat", "1,5 soat", "2 soat"], correct: 1 },
  { id: 2, text: "Toshbaqa 1 minutda 2 metr yo'l bosadi. 420 metrni necha soatda bosib o'tadi.", options: ["1 soat", "1,25 soat", "1,5 soat", "3,5 soat"], correct: 3 },
  { id: 3, text: "Shilliqqurt 1 minutda 0,5 metr masofani bosib o'tsa, 20 metrni qancha vaqtda bosib o'tadi.", options: ["30", "40", "20", "10"], correct: 1 },
  { id: 4, text: "a sonining 36 % i, 108 ning 24 % iga teng. a sonini toping.", options: ["36", "108", "72", "54"], correct: 2 },
  { id: 5, text: "14 ga bo'linadigan ikki xonali sonlar nechta?", options: ["6 ta", "8 ta", "9 ta", "7 ta"], correct: 3 },
  { id: 6, text: "Nechta ikki xonali son 50 ning bo'luvchisi bo'ladi?", options: ["2", "3", "4", "5"], correct: 1 },
  { id: 7, text: "Gul do'konida qizil atirguldan 3 xil guldasta va oq atirguldan 2 xil guldasta yasalgan. Bu guldastalardan 1 tasini olishning nechta usuli bor?", options: ["4", "5", "9", "12"], correct: 1 },
  { id: 8, text: "Gul do'konida qizil atirguldan 4 xil guldasta va oq atirguldan 2 xil guldasta yasalgan. Bu guldastalardan 1 tasini olishning nechta usuli bor?", options: ["8", "60", "6", "12"], correct: 2 },
  { id: 9, text: "Savatda 3 xil 3 dona meva bor. Ularni tokchaga necha xil usulda taxlasa bo'ladi?", options: ["5", "6", "4", "8"], correct: 1 },
  { id: 10, text: "Nigina opa qulupnayli murabbo tayyorlash uchun 1 kg qulupnayga 1,25 kg shakar soladi. 9 kg qulupnayli murabbo tayyorlash uchun necha kg qulupnay va necha kg shakar kerak bo'ladi?", options: ["3; 6", "4; 5", "7; 2", "4; 6"], correct: 1 },
  { id: 11, text: "Rasmda muntazam uchburchak va kvadrat berilgan. Kvadratning yuzi 36 ga teng bo'lsa, uchburchakning perimetrini toping.", options: ["18", "16", "24", "12"], correct: 0 },
  { id: 12, text: "Rasmda muntazam uchburchak va kvadrat berilgan. Kvadratning yuzi 4 ga teng bo'lsa, uchburchakning yuzini toping.", options: ["√3", "2√3", "4√3", "3"], correct: 0 },
  { id: 13, text: "Rasmda muntazam uchburchak va kvadrat berilgan. Kvadratning yuzi 4 ga teng bo'lsa, uchburchakning perimetrini toping.", options: ["6", "8", "10", "12"], correct: 0 },
  { id: 14, text: "2 ta sonning yig'indisi 220 ga teng. Ularning nisbati 10 ga teng bo'lsa, shu sonlarning musbat ayirmasini toping.", options: ["160", "170", "180", "190"], correct: 2 },
  { id: 15, text: "2 ta sonning yig'indisi 220 ga teng. Ularning nisbati 9 ga teng bo'lsa, shu sonlarning eng kattasini toping.", options: ["200", "198", "196", "194"], correct: 1 },
  { id: 16, text: "a, b natural sonlar uchun a + b/2 = 100 tenglik o'rinli bo'lsa, a + b ning eng katta qiymatini toping.", options: ["200", "250", "300", "199"], correct: 3 },
  { id: 17, text: "Aka ukasidan 10 yosh katta va ularning yoshlari nisbati 3:1 kabi. Necha yildan so'ng ularning yoshlari nisbati 2:1 nisbatda bo'ladi?", options: ["4", "5", "10", "8"], correct: 1 },
  { id: 18, text: "Mahsulotning narxi 55000 so'm edi. Agar mahsulot narxi 44000 so'mga tushirilsa, mahsulot uchun necha foiz chegirma bo'lgan?", options: ["11%", "20%", "25%", "40%"], correct: 1 },
  { id: 19, text: "Ko'paytuvchilarga ajrating: 6ab²c - 18abc", options: ["6ab(c - 3)", "6abc(b - 2)", "6abc(b - 3)", "abc(b - 18)"], correct: 2 },
  { id: 20, text: "Ko'paytuvchilarga ajrating: 8abc² - 16abc", options: ["8ab(c - 3)", "8abc(c - 2)", "8abc(c - 3)", "abc(b - 18)"], correct: 1 },
  { id: 21, text: "Tomonlari 5, 5, 6 cm bo'lgan parallelepipedning to'la sirtining yuzini toping.", options: ["150", "180", "170", "200"], correct: 2 },
  { id: 22, text: "10 cm³ hajmlik idishga necha litr suv ketadi?", options: ["0,01", "0,1", "1", "10"], correct: 0 },
  { id: 23, text: "200 litr necha (dm³) ga teng.", options: ["0,2", "200", "2", "20"], correct: 1 },
  { id: 24, text: "Kubning qirrasi 8 ga teng. Kub hajmini toping.", options: ["512", "256", "128", "64"], correct: 0 },
  { id: 25, text: "Shunday sonni topingki, u sonni 19 ga ko'paytirib, 9 ni ayirsa 200 ga teng bo'lsin.", options: ["13", "12", "11", "14"], correct: 2 },
  { id: 26, text: "Teng yonli uchburchakda AC = BC ≠ AB bo'lsa, uchburchakning qaysi burchaklari teng.", options: ["∠A = ∠C", "∠A = ∠B", "∠B = ∠C", "∠A = ∠C = ∠B"], correct: 1 },
  { id: 27, text: "(-13)² + 14 · (-12) ni hisoblang.", options: ["2", "3", "-1", "1"], correct: 3 },
  { id: 28, text: "(-12)² - 11 · 12 ni hisoblang.", options: ["-12", "310", "-276", "12"], correct: 3 },
  { id: 29, text: "Sport zalda 8 ta O'zbekistonlik, 10 ta Qozog'istonlik sportchilar bor. Musobaqaga 1 ta o'zbek va 1 ta qozoq sportchilarini necha xil usulda tanlab olish mumkin.", options: ["40", "80", "36", "72"], correct: 1 },
  { id: 30, text: "To'g'ri burchakli parallelepipedning qirralari 3, 4, 5 cm ga teng. Parallelepipedning eng katta yoq yuzini toping.", options: ["12", "10", "7,5", "20"], correct: 3 },
  { id: 31, text: "To'g'ri burchakli parallelepipedning qirralari 6, 8, 10 cm ga teng Parallelepipedning eng katta yoq yuzini toping.", options: ["80", "36", "48", "30"], correct: 0 },
  { id: 32, text: "Tog'ri burchakli uchburchakning katetlari 3 va 4 ga teng. Uchburchak yuzini toping.", options: ["12", "3", "6", "24"], correct: 2 },
  { id: 33, text: "Akbar 2 litrlik murabboni sig'imi 50 cm³ bo'lgan nechta idishga quyadi?", options: ["12", "36", "24", "40"], correct: 3 },
  { id: 34, text: "Soddalashtiring: (2a² - 6a³) · 2a", options: ["4a³ - 12a⁴", "4a² + 12a⁴", "4a⁴ - 12a³", "12a⁴ - 4a³"], correct: 0 },
  { id: 35, text: "Soddalashtiring: (2a² + 6a) : 2a", options: ["a + 2", "3 - a", "a + 3", "a + 4"], correct: 2 },
  { id: 36, text: "3 - √7 soniga qarama-qarshi sonni toping.", options: ["-√7 + 3", "-3 + √7", "7 - √3", "-7 + √3"], correct: 1 },
  { id: 37, text: "2(x - 3) + 7 = 2x tenglamani yeching.", options: ["2", "∅", "4", "5"], correct: 1 },
  { id: 38, text: "2(x + 3) - 5 = 1 - (x - 1) tenglamani yeching.", options: ["1", "2/3", "3", "1/3"], correct: 3 },
  { id: 39, text: "2/11 davriy kasrning verguldan keyingi 50-o'rinda turgan raqamini toping.", options: ["1", "8", "4", "6"], correct: 1 },
  { id: 40, text: "Hajmi 8 m³ ga teng bo'lgan kubning sirtini bo'yash uchun 1 m² ga 250 ml bo'yoq ketsa, kubning to'la sirtini bo'yash uchun necha litr bo'yoq ketadi?", options: ["6000", "600", "60", "6"], correct: 3 },
  { id: 41, text: "Agar a + b = 320, a/b = 39 tengliklar berilgan bo'lsa, a - b ning qiymatini toping.", options: ["299", "302", "304", "307"], correct: 2 },
  { id: 42, text: "Agar a + b = 64, a/b = 7 tengliklar berilgan bo'lsa, a - b ning qiymatini toping.", options: ["48", "32", "24", "36"], correct: 0 },
  { id: 43, text: "Soddalashtiring: (x + 2) · (x² - 2x + 4) - 4", options: ["x³ + 4", "x³ - 4", "x³ + 8", "x³ - 8"], correct: 0 },
  { id: 44, text: "Soddalashtiring: (x - 2) · (x² + 2x + 4) + 4", options: ["x³ + 4", "x³ - 4", "x³ + 8", "x³ - 8"], correct: 1 },
  { id: 45, text: "Soddalashtiring: a(b - c) - b(c - a) - c(a - b)", options: ["2ab + 2ac", "2b - 2ac", "4ab - 2ac", "2ab - 2ac"], correct: 3 },
  { id: 46, text: "25 gacha bo'lgan tub sonlar yig'indisini toping.", options: ["114", "100", "144", "99"], correct: 1 },
  { id: 47, text: "30 dan 50 gacha bo'lgan tub sonlar yig'indisini toping.", options: ["160", "199", "94", "200"], correct: 1 },
  { id: 48, text: "Aylanadagi A, B, C va D nuqtalardan foydalanib, nechta vatar o'tkazish mumkin?", options: ["7 ta", "4 ta", "6 ta", "12 ta"], correct: 2 },
  { id: 49, text: "Agar x = 8,25 va y = -2,25 bo'lsa, x² - y² ning qiymatini hisoblang.", options: ["64", "63", "60", "54"], correct: 1 },
  { id: 50, text: "Agar x = 7,25 va y = 1,75 bo'lsa, x² - y² ning qiymatini hisoblang.", options: ["32", "30", "34", "49,5"], correct: 3 },
  { id: 51, text: "Agar x = 6,25 va y = -2,25 bo'lsa, x² - y² ning qiymatini hisoblang.", options: ["32", "30", "34", "49"], correct: 2 },
  { id: 52, text: "Agar xy = 2 va x + y = 3 bo'lsa, x²y + y²x ning qiymatini hisoblang.", options: ["1", "2", "4", "6"], correct: 3 },
  { id: 53, text: "Koordinatasi A(-5; 0) va B(5; 0) bo'lgan nuqtalar orasidagi masofani toping.", options: ["11", "9", "12", "10"], correct: 3 },
  { id: 54, text: "Koordinatasi A(-7; 0) va B(7; 0) bo'lgan nuqtalar orasidagi masofani toping.", options: ["14", "9", "12", "10"], correct: 0 },
  { id: 55, text: "ABC uchburchakda 2α = 64° tenglik o'rinli bo'lsa, β burchakning qiymatini toping.", options: ["84°", "54°", "45°", "92°"], correct: 0 },
  { id: 56, text: "Fabrikada ko'ylak tikish uchun 12 % mato ketadi. Ko'ylak tikish uchun 300 metr mato olingan bo'lsa, fabrikada qancha metr mato bo'lgan?", options: ["1600", "2000", "1800", "2500"], correct: 3 },
  { id: 57, text: "Korxonadagi matoni 16% idan ko'ylak tikildi. Bu uchun 320 metr mato ketdi. Korxonada jami qancha mato bor?", options: ["2000", "1900", "1600", "3000"], correct: 0 },
  { id: 58, text: "Soddalashtiring: (10 - 4a): a - 2", options: ["1", "10/a - 6", "a - 1", "2a/3 - 1"], correct: 1 },
  { id: 59, text: "Ifodani soddalashtiring: (4 + 8a): 2 - 3a", options: ["a + 3", "a - 2", "4", "2 + a"], correct: 3 },
  { id: 60, text: "Agar x = -5,25 va y = -2,25 bo'lsa, x² - xy + y² - xy ni hisoblang.", options: ["4", "16", "12", "9"], correct: 3 },
  { id: 61, text: "6,42 + 9/8 - 1,045 ni hisoblang.", options: ["6,4", "6,5", "6", "1,25"], correct: 1 },
  { id: 62, text: "Hisoblang: (-2,4):(-0,8) + 7", options: ["10", "40", "4", "16"], correct: 0 },
  { id: 63, text: "Hisoblang: (-1,2):(-0,2) + 5", options: ["10", "11", "12", "13"], correct: 1 },
  { id: 64, text: "Tenglamani yeching: 144: x = 36", options: ["4", "10", "8", "16"], correct: 0 },
  { id: 65, text: "2019 - 2x = 2021 tenglamani yeching.", options: ["1", "4", "11", "-1"], correct: 3 },
  { id: 66, text: "A, B, C, D nuqtalar berilgan AC kesmaning uzunligi 25 cm, BD kesma uzunligi 27 cm, AD kesma uzunligi 45 cm ga teng bo'lsa, BC kesma uzunligini toping.", options: ["11", "8", "10", "7"], correct: 3 },
  { id: 67, text: "ABC uchburchakning perimetri 22 ga teng bo'lsa, x ning qiymatini toping(Rasmga qarang).", options: ["1", "4", "3", "5"], correct: 1 },
  { id: 68, text: "ABC uchburchakning perimetri 45 ga teng bo'lsa, x ning qiymatini toping. (Rasmga qarang).", options: ["1", "2", "3", "4"], correct: 1 },
  { id: 69, text: "Quyidagi jadvalda mahsulotlarning narxlari berilgan. Jami mahsulotning narxini(so'm) toping. (Pomidor 9000-3kg, Baklajon 13000-4kg, Bodring 8000-5kg)", options: ["120000", "119000", "103000", "140000"], correct: 1 },
  { id: 70, text: "3 ta qopning jami og'irligi 84 kilogramm. Agar birinchi qop ikkinchi qopdan 5 kilogrammga og'ir, ikkinchi qop esa uchinchi qopdan 4 kilogrammga yengil bo'lsa, uchinchi qop og'irligini toping.", options: ["11", "25", "7", "29"], correct: 3 },
  { id: 71, text: "Kubning asosining yuzi 64 ga teng bo'lsa, kubning to'la sirtining yuzini toping.", options: ["100", "400", "384", "272"], correct: 2 },
  { id: 72, text: "Kubning asosining yuzi 49 ga teng bo'lsa, kubning to'la sirtining yuzini toping.", options: ["156", "256", "194", "294"], correct: 3 },
  { id: 73, text: "10 metr/sekund necha km/sekund ga teng.", options: ["0,1", "0,01", "0,001", "0,0001"], correct: 1 },
  { id: 74, text: "30 metr/sekund necha kilometr/sekund ga teng.", options: ["0,3", "0,03", "0,003", "0,0003"], correct: 1 },
  { id: 75, text: "Poyezdga 18 kishi chiqdi so'ng 6 kishi tushib qoldi va so'ng poyezda 31 ta odam qoldi. Dastlab poyezda nechta odam bo'lgan?", options: ["38", "19", "17", "15"], correct: 1 },
  { id: 76, text: "Sinfda 24 ta o'quvchi bor. Sinf o'quvchilar orasidan sinf sardorini tanlashning nechta usuli bor?", options: ["12", "40", "24", "72"], correct: 2 },
  { id: 77, text: "Tenglama nechta ildizga ega? 10 - 2x = 2(4 - x) + 2", options: ["yechimga ega emas", "Cheksiz ko'p", "1 ta", "2 ta"], correct: 1 },
  { id: 78, text: "Agar ikki sonning yig'indisi 600 ga, biri ikkinchisidan 2 marta katta bo'lsa, shu sonlardan kattasini toping.", options: ["200", "300", "400", "450"], correct: 2 },
  { id: 79, text: "Kubning to'la sirti 468 m² ga teng. Kubning bitta yog'i yuzini toping.", options: ["72 m²", "74 m²", "76 m²", "78 m²"], correct: 3 },
  { id: 80, text: "Uchburchakning bitta tomoni 30 ga, qolgan ikkita tomoni 8:7 nisbatda. Uchburchakning perimetri 60 ga teng bo'lsa, uchburchakning kichik tomonini toping.", options: ["14", "15", "16", "17"], correct: 0 },
  { id: 81, text: "Teng yonli uchburchakning asosidagi burchagi 70° ga teng bo'lsa, uchidagi burchagini toping.", options: ["30°", "35°", "40°", "45°"], correct: 2 },
  { id: 82, text: "Raqamlari ko'paytmasi 12 ga teng bo'lgan nechta ikki xonali son bor?", options: ["3 ta", "4 ta", "5 ta", "6 ta"], correct: 1 },
  { id: 83, text: "Kubning to'la sirti 54 cm² bo'lsa, kubning hajmini toping.", options: ["18 cm³", "27 cm³", "36 cm³", "54 cm³"], correct: 1 },
  { id: 84, text: "Agar a = 5; b = 3 bo'lsa, (a+b)/(a-b) ning qiymatini toping.", options: ["2", "4", "6", "8"], correct: 1 },
  { id: 85, text: "Doira radiusi 6 ga teng bo'lsa, doiraning yuzini toping.", options: ["18π", "36π", "72π", "12π"], correct: 1 },
  { id: 86, text: "Hisoblang: 5/6 : 15/24 + 1/2 : 1/4", options: ["8/3", "10/3", "7/2", "11/3"], correct: 1 },
  { id: 87, text: "1 dan 97 gacha bo'lgan natural sonlar ichida 6 raqami necha marta ishtirok etadi?", options: ["20", "19", "18", "17"], correct: 0 },
  { id: 88, text: "Hisoblang: 17/22 - 3/5", options: ["119/10", "19/110", "20/110", "15/110"], correct: 1 },
  { id: 89, text: "Aylana radiusi 3 cm bo'lsa, uning uzunligini(cm) toping.", options: ["9π", "5π", "6π", "3π"], correct: 2 },
  { id: 90, text: "Kubning to'la sirti 48 cm² ga teng. Kubning bitta yog'ining yuzini toping.", options: ["66 cm²", "8 cm³", "8 cm²", "16 cm²"], correct: 2 },
  { id: 91, text: "Doira radiusi 3 cm bo'lsa, uning yuzasini toping.", options: ["9π", "6π", "4π", "2π"], correct: 0 },
  { id: 92, text: "Fermada 250 kg meva bor. Birinchi do'konga ikkinchisiga qaraganda 4 marta ko'p yuk yuborildi. Birinchi do'konga qancha meva yuborilgan?", options: ["50", "150", "200", "240"], correct: 2 },
  { id: 93, text: "225 dan qanday eng katta natural sonni ayirsak 144 dan katta bo'ladi?", options: ["80", "81", "79", "78"], correct: 0 },
  { id: 94, text: "Tenglamani yeching: 2(3 - x) = 2(3 - x) - 5", options: ["0", "1", "Cheksiz ko'p yechim", "yechimga ega emas"], correct: 3 },
  { id: 95, text: "Berilgan ma'lumotlardan foydalanib, ∠AOB + ∠BOD ni hisoblang. (AOB=30°)", options: ["70°", "140°", "210°", "180°"], correct: 3 },
  { id: 96, text: "Kvadratning tomoni 3 ga teng. Kvadratning yuzini toping?", options: ["12", "9", "8", "10"], correct: 1 },
  { id: 97, text: "Raqamlar ko'paytmasi 6 ga teng bo'lgan ikki xonali sonlar nechta?", options: ["4 ta", "3 ta", "2 ta", "1 ta"], correct: 0 },
  { id: 98, text: "Kvadratning perimetri 16 cm ga teng bo'lsa, kvadrat tomonini toping.", options: ["4m", "4 cm", "4 dm", "8 cm"], correct: 1 },
  { id: 99, text: "Radiusi 3 ga teng bo'lgan aylananing uzunligini toping (π = 3 deb oling).", options: ["16", "27", "18", "21"], correct: 2 },
  { id: 100, text: "Radiusi 15 ga teng bo'lgan doirani yuzini toping.", options: ["200π", "200π", "225", "225π"], correct: 3 }
];

export const variants = [];
for (let i = 0; i < questions.length; i += 10) {
  variants.push(questions.slice(i, i + 10));
}
